name: poc review de codigo
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Corriendo boton
        uses: crulises/boton@v0.0.3
        with:
          llm_endpoint: "https://esta-es-una-url-para-una-api.com/review"
          api_key: ${{ secrets.LLM_API_KEY }}
          github_token: ${{ secrets.GH_PAT }}
          prompt_file: "prompts.yml"